// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.2
// source: cv.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщение для резюме
type Resume struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                           // Уникальный идентификатор резюме
	CandidateName string `protobuf:"bytes,2,opt,name=candidate_name,json=candidateName,proto3" json:"candidate_name,omitempty"` // Имя кандидата
	Email         string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`                                      // Электронная почта кандидата
	Phone         string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`                                      // Телефон кандидата
	Experience    string `protobuf:"bytes,5,opt,name=experience,proto3" json:"experience,omitempty"`                            // Опыт работы
	Education     string `protobuf:"bytes,6,opt,name=education,proto3" json:"education,omitempty"`                              // Образование
}

func (x *Resume) Reset() {
	*x = Resume{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resume) ProtoMessage() {}

func (x *Resume) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resume.ProtoReflect.Descriptor instead.
func (*Resume) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{0}
}

func (x *Resume) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Resume) GetCandidateName() string {
	if x != nil {
		return x.CandidateName
	}
	return ""
}

func (x *Resume) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Resume) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Resume) GetExperience() string {
	if x != nil {
		return x.Experience
	}
	return ""
}

func (x *Resume) GetEducation() string {
	if x != nil {
		return x.Education
	}
	return ""
}

// Сообщение для вакансии
type Vacancy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                  // Уникальный идентификатор вакансии
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`             // Название вакансии
	Company     string `protobuf:"bytes,3,opt,name=company,proto3" json:"company,omitempty"`         // Название компании
	Location    string `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`       // Местоположение
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"` // Описание вакансии
}

func (x *Vacancy) Reset() {
	*x = Vacancy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vacancy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vacancy) ProtoMessage() {}

func (x *Vacancy) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vacancy.ProtoReflect.Descriptor instead.
func (*Vacancy) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{1}
}

func (x *Vacancy) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Vacancy) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Vacancy) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Vacancy) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Vacancy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Запрос для создания резюме
type CreateResumeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resume *Resume `protobuf:"bytes,1,opt,name=resume,proto3" json:"resume,omitempty"` // Резюме для создания
}

func (x *CreateResumeRequest) Reset() {
	*x = CreateResumeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResumeRequest) ProtoMessage() {}

func (x *CreateResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResumeRequest.ProtoReflect.Descriptor instead.
func (*CreateResumeRequest) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResumeRequest) GetResume() *Resume {
	if x != nil {
		return x.Resume
	}
	return nil
}

// Ответ на создание резюме
type CreateResumeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resume *Resume `protobuf:"bytes,1,opt,name=resume,proto3" json:"resume,omitempty"` // Созданное резюме
}

func (x *CreateResumeResponse) Reset() {
	*x = CreateResumeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResumeResponse) ProtoMessage() {}

func (x *CreateResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResumeResponse.ProtoReflect.Descriptor instead.
func (*CreateResumeResponse) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{3}
}

func (x *CreateResumeResponse) GetResume() *Resume {
	if x != nil {
		return x.Resume
	}
	return nil
}

// Запрос для получения резюме по ID
type GetResumeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Уникальный идентификатор резюме
}

func (x *GetResumeRequest) Reset() {
	*x = GetResumeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResumeRequest) ProtoMessage() {}

func (x *GetResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResumeRequest.ProtoReflect.Descriptor instead.
func (*GetResumeRequest) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{4}
}

func (x *GetResumeRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Ответ на получение резюме
type GetResumeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resume *Resume `protobuf:"bytes,1,opt,name=resume,proto3" json:"resume,omitempty"` // Найденное резюме
}

func (x *GetResumeResponse) Reset() {
	*x = GetResumeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResumeResponse) ProtoMessage() {}

func (x *GetResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResumeResponse.ProtoReflect.Descriptor instead.
func (*GetResumeResponse) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{5}
}

func (x *GetResumeResponse) GetResume() *Resume {
	if x != nil {
		return x.Resume
	}
	return nil
}

// Запрос для обновления резюме
type UpdateResumeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resume *Resume `protobuf:"bytes,1,opt,name=resume,proto3" json:"resume,omitempty"` // Резюме с обновленными данными
}

func (x *UpdateResumeRequest) Reset() {
	*x = UpdateResumeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResumeRequest) ProtoMessage() {}

func (x *UpdateResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResumeRequest.ProtoReflect.Descriptor instead.
func (*UpdateResumeRequest) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateResumeRequest) GetResume() *Resume {
	if x != nil {
		return x.Resume
	}
	return nil
}

// Ответ на обновление резюме
type UpdateResumeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resume *Resume `protobuf:"bytes,1,opt,name=resume,proto3" json:"resume,omitempty"` // Обновленное резюме
}

func (x *UpdateResumeResponse) Reset() {
	*x = UpdateResumeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResumeResponse) ProtoMessage() {}

func (x *UpdateResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResumeResponse.ProtoReflect.Descriptor instead.
func (*UpdateResumeResponse) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateResumeResponse) GetResume() *Resume {
	if x != nil {
		return x.Resume
	}
	return nil
}

// Запрос для удаления резюме
type DeleteResumeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Уникальный идентификатор резюме для удаления
}

func (x *DeleteResumeRequest) Reset() {
	*x = DeleteResumeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResumeRequest) ProtoMessage() {}

func (x *DeleteResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResumeRequest.ProtoReflect.Descriptor instead.
func (*DeleteResumeRequest) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResumeRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Ответ на удаление резюме
type DeleteResumeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Успешность удаления
}

func (x *DeleteResumeResponse) Reset() {
	*x = DeleteResumeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResumeResponse) ProtoMessage() {}

func (x *DeleteResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResumeResponse.ProtoReflect.Descriptor instead.
func (*DeleteResumeResponse) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteResumeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Запрос для создания вакансии
type CreateVacancyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vacancy *Vacancy `protobuf:"bytes,1,opt,name=vacancy,proto3" json:"vacancy,omitempty"` // Вакансия для создания
}

func (x *CreateVacancyRequest) Reset() {
	*x = CreateVacancyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVacancyRequest) ProtoMessage() {}

func (x *CreateVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVacancyRequest.ProtoReflect.Descriptor instead.
func (*CreateVacancyRequest) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{10}
}

func (x *CreateVacancyRequest) GetVacancy() *Vacancy {
	if x != nil {
		return x.Vacancy
	}
	return nil
}

// Ответ на создание вакансии
type CreateVacancyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vacancy *Vacancy `protobuf:"bytes,1,opt,name=vacancy,proto3" json:"vacancy,omitempty"` // Созданная вакансия
}

func (x *CreateVacancyResponse) Reset() {
	*x = CreateVacancyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVacancyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVacancyResponse) ProtoMessage() {}

func (x *CreateVacancyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVacancyResponse.ProtoReflect.Descriptor instead.
func (*CreateVacancyResponse) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{11}
}

func (x *CreateVacancyResponse) GetVacancy() *Vacancy {
	if x != nil {
		return x.Vacancy
	}
	return nil
}

// Запрос для получения вакансии по ID
type GetVacancyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Уникальный идентификатор вакансии
}

func (x *GetVacancyRequest) Reset() {
	*x = GetVacancyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVacancyRequest) ProtoMessage() {}

func (x *GetVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVacancyRequest.ProtoReflect.Descriptor instead.
func (*GetVacancyRequest) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{12}
}

func (x *GetVacancyRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Ответ на получение вакансии
type GetVacancyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vacancy *Vacancy `protobuf:"bytes,1,opt,name=vacancy,proto3" json:"vacancy,omitempty"` // Найденная вакансия
}

func (x *GetVacancyResponse) Reset() {
	*x = GetVacancyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVacancyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVacancyResponse) ProtoMessage() {}

func (x *GetVacancyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVacancyResponse.ProtoReflect.Descriptor instead.
func (*GetVacancyResponse) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{13}
}

func (x *GetVacancyResponse) GetVacancy() *Vacancy {
	if x != nil {
		return x.Vacancy
	}
	return nil
}

// Запрос для обновления вакансии
type UpdateVacancyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vacancy *Vacancy `protobuf:"bytes,1,opt,name=vacancy,proto3" json:"vacancy,omitempty"` // Вакансия с обновленными данными
}

func (x *UpdateVacancyRequest) Reset() {
	*x = UpdateVacancyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVacancyRequest) ProtoMessage() {}

func (x *UpdateVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVacancyRequest.ProtoReflect.Descriptor instead.
func (*UpdateVacancyRequest) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateVacancyRequest) GetVacancy() *Vacancy {
	if x != nil {
		return x.Vacancy
	}
	return nil
}

// Ответ на обновление вакансии
type UpdateVacancyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vacancy *Vacancy `protobuf:"bytes,1,opt,name=vacancy,proto3" json:"vacancy,omitempty"` // Обновленная вакансия
}

func (x *UpdateVacancyResponse) Reset() {
	*x = UpdateVacancyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVacancyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVacancyResponse) ProtoMessage() {}

func (x *UpdateVacancyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVacancyResponse.ProtoReflect.Descriptor instead.
func (*UpdateVacancyResponse) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateVacancyResponse) GetVacancy() *Vacancy {
	if x != nil {
		return x.Vacancy
	}
	return nil
}

// Запрос для удаления вакансии
type DeleteVacancyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Уникальный идентификатор вакансии для удаления
}

func (x *DeleteVacancyRequest) Reset() {
	*x = DeleteVacancyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVacancyRequest) ProtoMessage() {}

func (x *DeleteVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVacancyRequest.ProtoReflect.Descriptor instead.
func (*DeleteVacancyRequest) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteVacancyRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Ответ на удаление вакансии
type DeleteVacancyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Успешность удаления
}

func (x *DeleteVacancyResponse) Reset() {
	*x = DeleteVacancyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVacancyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVacancyResponse) ProtoMessage() {}

func (x *DeleteVacancyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVacancyResponse.ProtoReflect.Descriptor instead.
func (*DeleteVacancyResponse) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteVacancyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Запрос для получения всех резюме
type GetAllResumesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllResumesRequest) Reset() {
	*x = GetAllResumesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllResumesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResumesRequest) ProtoMessage() {}

func (x *GetAllResumesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResumesRequest.ProtoReflect.Descriptor instead.
func (*GetAllResumesRequest) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{18}
}

// Ответ на получение всех резюме
type GetAllResumesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resumes []*Resume `protobuf:"bytes,1,rep,name=resumes,proto3" json:"resumes,omitempty"` // Список всех резюме
}

func (x *GetAllResumesResponse) Reset() {
	*x = GetAllResumesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllResumesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResumesResponse) ProtoMessage() {}

func (x *GetAllResumesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResumesResponse.ProtoReflect.Descriptor instead.
func (*GetAllResumesResponse) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{19}
}

func (x *GetAllResumesResponse) GetResumes() []*Resume {
	if x != nil {
		return x.Resumes
	}
	return nil
}

type GetAllVacanciesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllVacanciesRequest) Reset() {
	*x = GetAllVacanciesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllVacanciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllVacanciesRequest) ProtoMessage() {}

func (x *GetAllVacanciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllVacanciesRequest.ProtoReflect.Descriptor instead.
func (*GetAllVacanciesRequest) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{20}
}

// Ответ на получение всех вакансий
type GetAllVacanciesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vacancies []*Vacancy `protobuf:"bytes,1,rep,name=vacancies,proto3" json:"vacancies,omitempty"` // Список всех вакансий
}

func (x *GetAllVacanciesResponse) Reset() {
	*x = GetAllVacanciesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllVacanciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllVacanciesResponse) ProtoMessage() {}

func (x *GetAllVacanciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllVacanciesResponse.ProtoReflect.Descriptor instead.
func (*GetAllVacanciesResponse) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{21}
}

func (x *GetAllVacanciesResponse) GetVacancies() []*Vacancy {
	if x != nil {
		return x.Vacancies
	}
	return nil
}

var File_cv_proto protoreflect.FileDescriptor

var file_cv_proto_rawDesc = []byte{
	0x0a, 0x08, 0x63, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa9, 0x01, 0x0a, 0x06, 0x52,
	0x65, 0x73, 0x75, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63,
	0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x65,
	0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78,
	0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x64, 0x75, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x64, 0x75,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x87, 0x01, 0x0a, 0x07, 0x56, 0x61, 0x63, 0x61, 0x6e,
	0x63, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x36, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x07, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6d,
	0x65, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x22, 0x36, 0x0a, 0x13, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65,
	0x73, 0x75, 0x6d, 0x65, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x22, 0x25, 0x0a, 0x13,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x3a, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56,
	0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a,
	0x07, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x07, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63,
	0x79, 0x22, 0x3b, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e,
	0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x07, 0x76, 0x61,
	0x63, 0x61, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x56, 0x61,
	0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x07, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x22, 0x23,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x07, 0x76, 0x61, 0x63,
	0x61, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x56, 0x61, 0x63,
	0x61, 0x6e, 0x63, 0x79, 0x52, 0x07, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x22, 0x3a, 0x0a,
	0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x07, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79,
	0x52, 0x07, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x22, 0x3b, 0x0a, 0x15, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x22, 0x0a, 0x07, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x07, 0x76,
	0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x22, 0x26, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x31,
	0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6d,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3a, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x21, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x07, 0x72, 0x65,
	0x73, 0x75, 0x6d, 0x65, 0x73, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x56,
	0x61, 0x63, 0x61, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x41, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x09, 0x76, 0x61,
	0x63, 0x61, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x09, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x69,
	0x65, 0x73, 0x32, 0xfc, 0x04, 0x0a, 0x12, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x12, 0x14, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x12, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6d,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x12, 0x14, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x12, 0x14, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x61,
	0x63, 0x61, 0x6e, 0x63, 0x79, 0x12, 0x15, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x61,
	0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x56, 0x61, 0x63, 0x61, 0x6e,
	0x63, 0x79, 0x12, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x61, 0x63, 0x61,
	0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x12, 0x17,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e,
	0x63, 0x79, 0x12, 0x15, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e,
	0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e,
	0x63, 0x79, 0x12, 0x15, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e,
	0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cv_proto_rawDescOnce sync.Once
	file_cv_proto_rawDescData = file_cv_proto_rawDesc
)

func file_cv_proto_rawDescGZIP() []byte {
	file_cv_proto_rawDescOnce.Do(func() {
		file_cv_proto_rawDescData = protoimpl.X.CompressGZIP(file_cv_proto_rawDescData)
	})
	return file_cv_proto_rawDescData
}

var file_cv_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_cv_proto_goTypes = []interface{}{
	(*Resume)(nil),                  // 0: Resume
	(*Vacancy)(nil),                 // 1: Vacancy
	(*CreateResumeRequest)(nil),     // 2: CreateResumeRequest
	(*CreateResumeResponse)(nil),    // 3: CreateResumeResponse
	(*GetResumeRequest)(nil),        // 4: GetResumeRequest
	(*GetResumeResponse)(nil),       // 5: GetResumeResponse
	(*UpdateResumeRequest)(nil),     // 6: UpdateResumeRequest
	(*UpdateResumeResponse)(nil),    // 7: UpdateResumeResponse
	(*DeleteResumeRequest)(nil),     // 8: DeleteResumeRequest
	(*DeleteResumeResponse)(nil),    // 9: DeleteResumeResponse
	(*CreateVacancyRequest)(nil),    // 10: CreateVacancyRequest
	(*CreateVacancyResponse)(nil),   // 11: CreateVacancyResponse
	(*GetVacancyRequest)(nil),       // 12: GetVacancyRequest
	(*GetVacancyResponse)(nil),      // 13: GetVacancyResponse
	(*UpdateVacancyRequest)(nil),    // 14: UpdateVacancyRequest
	(*UpdateVacancyResponse)(nil),   // 15: UpdateVacancyResponse
	(*DeleteVacancyRequest)(nil),    // 16: DeleteVacancyRequest
	(*DeleteVacancyResponse)(nil),   // 17: DeleteVacancyResponse
	(*GetAllResumesRequest)(nil),    // 18: GetAllResumesRequest
	(*GetAllResumesResponse)(nil),   // 19: GetAllResumesResponse
	(*GetAllVacanciesRequest)(nil),  // 20: GetAllVacanciesRequest
	(*GetAllVacanciesResponse)(nil), // 21: GetAllVacanciesResponse
}
var file_cv_proto_depIdxs = []int32{
	0,  // 0: CreateResumeRequest.resume:type_name -> Resume
	0,  // 1: CreateResumeResponse.resume:type_name -> Resume
	0,  // 2: GetResumeResponse.resume:type_name -> Resume
	0,  // 3: UpdateResumeRequest.resume:type_name -> Resume
	0,  // 4: UpdateResumeResponse.resume:type_name -> Resume
	1,  // 5: CreateVacancyRequest.vacancy:type_name -> Vacancy
	1,  // 6: CreateVacancyResponse.vacancy:type_name -> Vacancy
	1,  // 7: GetVacancyResponse.vacancy:type_name -> Vacancy
	1,  // 8: UpdateVacancyRequest.vacancy:type_name -> Vacancy
	1,  // 9: UpdateVacancyResponse.vacancy:type_name -> Vacancy
	0,  // 10: GetAllResumesResponse.resumes:type_name -> Resume
	1,  // 11: GetAllVacanciesResponse.vacancies:type_name -> Vacancy
	2,  // 12: RecruitmentService.CreateResume:input_type -> CreateResumeRequest
	4,  // 13: RecruitmentService.GetResume:input_type -> GetResumeRequest
	18, // 14: RecruitmentService.GetAllResumes:input_type -> GetAllResumesRequest
	6,  // 15: RecruitmentService.UpdateResume:input_type -> UpdateResumeRequest
	8,  // 16: RecruitmentService.DeleteResume:input_type -> DeleteResumeRequest
	10, // 17: RecruitmentService.CreateVacancy:input_type -> CreateVacancyRequest
	12, // 18: RecruitmentService.GetVacancy:input_type -> GetVacancyRequest
	20, // 19: RecruitmentService.GetAllVacancies:input_type -> GetAllVacanciesRequest
	14, // 20: RecruitmentService.UpdateVacancy:input_type -> UpdateVacancyRequest
	16, // 21: RecruitmentService.DeleteVacancy:input_type -> DeleteVacancyRequest
	3,  // 22: RecruitmentService.CreateResume:output_type -> CreateResumeResponse
	5,  // 23: RecruitmentService.GetResume:output_type -> GetResumeResponse
	19, // 24: RecruitmentService.GetAllResumes:output_type -> GetAllResumesResponse
	7,  // 25: RecruitmentService.UpdateResume:output_type -> UpdateResumeResponse
	9,  // 26: RecruitmentService.DeleteResume:output_type -> DeleteResumeResponse
	11, // 27: RecruitmentService.CreateVacancy:output_type -> CreateVacancyResponse
	13, // 28: RecruitmentService.GetVacancy:output_type -> GetVacancyResponse
	21, // 29: RecruitmentService.GetAllVacancies:output_type -> GetAllVacanciesResponse
	15, // 30: RecruitmentService.UpdateVacancy:output_type -> UpdateVacancyResponse
	17, // 31: RecruitmentService.DeleteVacancy:output_type -> DeleteVacancyResponse
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_cv_proto_init() }
func file_cv_proto_init() {
	if File_cv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resume); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vacancy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResumeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResumeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResumeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResumeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateResumeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateResumeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResumeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResumeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVacancyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVacancyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVacancyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVacancyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVacancyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVacancyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteVacancyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteVacancyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllResumesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllResumesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllVacanciesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllVacanciesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cv_proto_goTypes,
		DependencyIndexes: file_cv_proto_depIdxs,
		MessageInfos:      file_cv_proto_msgTypes,
	}.Build()
	File_cv_proto = out.File
	file_cv_proto_rawDesc = nil
	file_cv_proto_goTypes = nil
	file_cv_proto_depIdxs = nil
}
